### ISSUE TITLE
Nightly feature stdsimd has been removed

### ISSUE THREAD

**Issue by jayvdb** [jvdd/argminmax#61]
The commit removing stdsimd is https://github.com/rust-lang/rust/commit/ea37e8091fe87ae0a7e204c034e7d55061e56790

Relevant tracking issues? https://github.com/rust-lang/rust/issues/27731 and https://github.com/rust-lang/rust/issues/48556

**Comment by BrettForr** [comment]
Hi, sorry I'm new to the space so don't know conventions etc. What's the path to resolving this? Is it work to do in this crate or something that needs to be done with nightly rust? I tried switching to an earlier version of nightly rust but that caused some other things to break for me, so wondering if I should keep going down that path or wait for a soon-coming fix.
