### ISSUE TITLE
:sparkles: implement ArgMinMax trait for other types

### ISSUE THREAD

**Issue by jvdd** [jvdd/argminmax#9]
Currently the ArgMinMax trait is only implemented for `ndarray::ArrayView1`.  
It might be interesting to implement the trait for 
- `Vec`
- `array`?

Credits @minimalrust, see https://github.com/minimalrust/argmm/issues/8

**Comment by minimalrust** [comment]
Incredible work! You’re quickly becoming my new favourite person 😁. Loving the new benchmarking too.

**Comment by jvdd** [comment]
I appreciate the kind words! :blush: 
Indeed, the continuous benchmarking of codspeed is an awesome extension for performance oriented packages :)
